# 3nd try

In [643]:
import json
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import pandas as pd 

In [644]:
TRAIN_FILE_PATH = "data/train.json"

with open(TRAIN_FILE_PATH, "r", encoding="utf-8") as f:
    train_data = json.load(f)
# train_data

In [645]:
len(train_data)

12330

In [646]:
train_data[0].keys()

dict_keys(['ner_tags', 'ner_ids', 'tokens', 'space_after'])

In [647]:
TEST_FILE_PATH = "data/test.json"

with open(TEST_FILE_PATH, "r", encoding="utf-8") as f:
    test_data = json.load(f)
# test_data

In [648]:
len(test_data)

2421

In [649]:
TAG2ID_FILE_PATH = "data/tag_to_id.json"

with open(TAG2ID_FILE_PATH, "r", encoding="utf-8") as f:
    tag2id = json.load(f)
# tag2id

In [650]:
max([len(data['tokens']) for data in train_data])

561

In [651]:
# maxim = 0
# for data in train_data:
#     if maxim < len(data['tokens']):
#         maxim = len(data['tokens'])
#         maxim_data = data
# print(maxim_data['tokens'])
# print(len(maxim_data['tokens']))

In [652]:
num_tokens_over_512 = 0
for data in train_data:
    if len(data['tokens']) > 512:
        num_tokens_over_512 += 1
        data['tokens'] = data['tokens'][:512]
print(num_tokens_over_512)

2


In [653]:
num_tokens_over_512 = 0
for data in train_data:
    if len(data['tokens']) > 510:
        num_tokens_over_512 += 1
        for key in data.keys():
            data[key] = data[key][:510]
print(num_tokens_over_512)

2


In [654]:
num = 0
for data in train_data:
    if len(data['tokens']) > 126:
        num += 1
        for key in data.keys():
            data[key] = data[key][:126]
print(num)

236


In [655]:
num_tokens_over_512 = 0
for data in test_data:
    if len(data['tokens']) > 126:
        num_tokens_over_512 += 1
print(num_tokens_over_512)

0


## Split Data

In [656]:
X = [data['tokens'] for data in train_data]
y = [data['ner_ids'] for data in train_data]

In [657]:
# X = [token for data in train_data for token in data['tokens']]
# X

In [658]:
# y = [ner_id for data in train_data for ner_id in data['ner_ids']]

In [659]:
X_train, X_validate, y_train, y_validate = train_test_split(X, y, test_size=0.2, random_state=35)

In [660]:
X

[['În',
  'România',
  ',',
  'ca',
  'de',
  'altfel',
  'în',
  'întreaga',
  'Europă',
  ',',
  'stand',
  'up',
  '-ul',
  'este',
  'forma',
  'de',
  'divertisment',
  'cea',
  'mai',
  'îndrăgită',
  'de',
  'tineri',
  'în',
  'acest',
  'moment',
  ',',
  'comediantii',
  'reușind',
  'să',
  'umple',
  'săli',
  'care',
  'erau',
  'destinate',
  'mai',
  'degrabă',
  'artiștilor',
  'din',
  'zona',
  'muzicii',
  'pop',
  'rock',
  ',',
  'iar',
  'Badea',
  ',',
  'Bordea',
  'și',
  'Micutzu',
  'sunt',
  'printre',
  'cei',
  'care',
  'au',
  'contribuit',
  'direct',
  'la',
  'succesul',
  'acestei',
  'forme',
  'de',
  'divertisment',
  'în',
  'țara',
  'noastră',
  '.'],
 ['Se',
  'estimează',
  'că',
  'în',
  'prezent',
  'acestea',
  'sunt',
  'utilizate',
  'de',
  'mai',
  'mult',
  'de',
  '50',
  'de',
  'milioane',
  'de',
  'persoane',
  'fizice',
  'și',
  'juridice',
  'din',
  'lumea',
  'întreagă',
  '.'],
 ['Cartea',
  'cuprinde',
  'o',
  'suită',
 

In [661]:
y

[[0,
  3,
  0,
  0,
  0,
  0,
  0,
  0,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 13, 13, 13, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0,
  0,
  0,
  0,
  0,
  13,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  13,
  0,
  0,
  0,
  13,
  0,
  0,
  0,
  0,
  0,
  0,
  13,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  13,
  0,
  0,
  0,
  13,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  9,
  9,
  9,
  0,
  2,
  2,
  2,
  0,
  0,
  9,
  9,
  9,
  0,
  0,
  6,
  6,
  0],

## Apply Bert

In [662]:
len(list(tag2id.keys()))

16

In [663]:
import torch # Neural Networks
import torch.nn.functional as F
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, RandomSampler, SequentialSampler
from transformers import AutoTokenizer, AutoModel, AdamW # Transformers
from sklearn.manifold import TSNE # Data projection
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [664]:
class DatasetTransformer(Dataset):
    def __init__(self, X, y, tokenizer):
        self.tokenizer = tokenizer
        self.X = X
        self.y = y
            
    def __len__(self):
        return len(self.y)
    
    def __getitem__(self, idx):
        text = self.X[idx]
        label = self.y[idx]
        
        # preprocess text
        # Remove cedilla diacritics as suggested in
        # https://huggingface.co/dumitrescustefan/bert-base-romanian-uncased-v1
        text = [
            word.replace("ţ", "ț").replace("ş", "ș").replace("Ţ", "Ț").replace("Ş", "Ș") 
            for word in text
        ]
        
        text = ['CLS'] + text + ['SEP']
        label = [0] + label + [0] # !!!!!!!!!!!!!!!! avem si clasa 0
        mask = [1] * len(text)
        
        padding_len = 128 - len(text)
        text += ['PAD'] * padding_len
        label += [0] * padding_len
        mask += [0] * padding_len
        
        text_tensor = torch.tensor(self.tokenizer.convert_tokens_to_ids(text))
        
        return text_tensor, torch.tensor(label), torch.tensor(mask)

In [665]:
tokenizer = AutoTokenizer.from_pretrained(
    "dumitrescustefan/bert-base-romanian-uncased-v1", do_lower_case=True)

In [666]:
tokenizer.convert_tokens_to_ids('[PAD]')

0

## Create DataLoaders

In [667]:
ds_train = DatasetTransformer(X_train, y_train, tokenizer)
ds_val = DatasetTransformer(X_validate, y_validate, tokenizer)

BATCH_SIZE = 32

train_dataloader = DataLoader(
    ds_train, 
    sampler=RandomSampler(ds_train), 
    batch_size=BATCH_SIZE
)

val_dataloader = DataLoader(
    ds_val, 
    sampler=SequentialSampler(ds_val), 
    batch_size=BATCH_SIZE
)

In [668]:
transformer = AutoModel.from_pretrained("dumitrescustefan/bert-base-romanian-uncased-v1")

Some weights of the model checkpoint at dumitrescustefan/bert-base-romanian-uncased-v1 were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [669]:
transformer

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(50000, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [670]:
def my_loss_fn(output, target, mask):
    lfn = nn.CrossEntropyLoss()
    active_loss = mask.view(-1) == 1
    active_logits = output.view(-1, 16)
    active_labels = torch.where(
        active_loss,
        target.view(-1),
        torch.tensor(lfn.ignore_index).type_as(target)
    )
    loss = lfn(active_logits, active_labels)
    return loss

In [671]:
class TransformerModel(nn.Module):
    def __init__(self, in_dim=768, no_classes=16):
        super(TransformerModel, self).__init__()
        # Get the romanian Transformer from the huggingface server
        self.transformer = AutoModel.from_pretrained("dumitrescustefan/bert-base-romanian-uncased-v1",return_dict=False)

        self.bert_drop_1 = nn.Dropout(0.3)

        # Add a linear layer for classification
        self.fc1 = nn.Linear(in_dim, no_classes)
        
    def forward(self, ids=None, mask=None, target_tag=None):
        o1, _ = self.transformer(ids, attention_mask=mask)
        bo_tag = self.bert_drop_1(o1)
        # TODO: ADD DROP

        tag = self.fc1(bo_tag)

        loss_tag = 0
        if target_tag is not None:
            loss_tag = my_loss_fn(tag, target_tag, mask)

        return tag, loss_tag

In [672]:
# Check if there's any available GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [673]:
# Instantiate our model and move it to GPU
model = TransformerModel().to(device)

# Freeze all the Transformer parameters
for p in model.transformer.parameters():
    p.requires_grad = False
# ... except for the bias terms
trainable_params_transformer = [p for (n, p) in model.transformer.named_parameters() if "bias" in n]
for p in trainable_params_transformer:
    p.requires_grad = True

# We'll train the final layer and the bias terms
trainable_params = list(model.fc1.parameters())
trainable_params.extend(list(trainable_params_transformer))

# Define our loss and optimizer
loss_fn = nn.CrossEntropyLoss()
# We'll use AdamW for the Transformer
optim = torch.optim.AdamW(trainable_params)

no_epochs = 20
best_val_loss = 999

Some weights of the model checkpoint at dumitrescustefan/bert-base-romanian-uncased-v1 were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [684]:
def train_epoch(model, optim, dataloader):
    """ Trains the model for one epoch and returns the loss together with a classification report
    """
    
    epoch_loss = 0
    # Put the model in training mode
    model.train()
    preds = []
    gt = []

    correct_labels = 0
    total_predictions = 0
    
    for idx, batch in tqdm(enumerate(dataloader)):
        # Reset gradients
        optim.zero_grad()
        
        inputs, labels, masks = batch
        # Move data to GPU
        inputs = inputs.to(device)
        labels = labels.to(device)
        masks = masks.to(device)
        
        output, loss = model(ids=inputs, mask=masks, target_tag=labels)
        
        # Calculate the loss and backpropagate
        loss.backward()
        # Update weights
        optim.step()
        
        epoch_loss += loss.item()
        
        probs = F.softmax(output, dim=-1)
        batch_preds = torch.argmax(probs, dim=1)

        preds.append(batch_preds.cpu().numpy())
        gt.append(labels.cpu().numpy())

        total_predictions += len(labels)

        break

    for i in range(len(preds)):
        if preds[i] == gt[i]:
            correct_labels += 1
    
    # Average the epoch losses
    epoch_loss /= len(dataloader)
    
    preds = np.concatenate(preds)
    gt = np.concatenate(gt)
    
    return epoch_loss, correct_labels / total_predictions

def eval(model, optim, dataloader):
    """ Trains the model for one epoch and returns the loss together with a classification report
    """
    
    epoch_loss = 0
    # Put the model in eval mode
    model.eval()
    preds = []
    gt = []

    correct_labels = 0
    total_predictions = 0
    
    with torch.no_grad():
        for idx, batch in tqdm(enumerate(dataloader)):
            # Reset gradients
            optim.zero_grad()
            
            inputs, labels, masks = batch
            # Move data to GPU
            inputs = inputs.to(device)
            labels = labels.to(device)
            masks = masks.to(device)
            
            output, loss = model(ids=inputs, mask=masks, target_tag=labels)
            epoch_loss += loss.item()
            print(output.shape)
            
            probs = F.softmax(output, dim=-1)
            print(probs)
            batch_preds = torch.argmax(probs, dim=2)
            print('batch_preds', batch_preds.shape, batch_preds)

            preds.append(batch_preds.cpu().numpy())
            gt.append(labels.cpu().numpy())

            total_predictions += len(labels)

    for i in range(len(preds)):
        if preds[i] == gt[i]:
            correct_labels += 1
    
    # Average the epoch losses
    epoch_loss /= len(dataloader)
    
    preds = np.concatenate(preds)
    gt = np.concatenate(gt)
    
    return epoch_loss, correct_labels / total_predictions

In [686]:
import numpy as np

pbar = tqdm(range(no_epochs))

train_losses = []
val_losses = []

train_accs = []
val_accs = []

for e in pbar:
    train_loss, train_acc = train_epoch(model, optim, train_dataloader)
    val_loss, val_acc = eval(model, loss_fn, val_dataloader)
    
    train_losses.append(train_loss)
    val_losses.append(val_loss)
    
    train_accs.append(train_acc)
    val_accs.append(val_acc)
    
    pbar.set_description(
        "Epoch: %s, t_loss: %.3f, v_loss: %.3f, t_acc: %.2f, v_acc: %.2f" % (e+1, train_loss, val_loss, train_acc, val_acc))
    
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), './best_transformer_model.pt')


0it [00:00, ?it/s]/20 [00:00<?, ?it/s]
C:\Users\preda\GoodIA\lib\site-packages\ipykernel_launcher.py:44: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


torch.Size([32, 128, 16])
tensor([[[9.8070e-01, 4.9026e-03, 2.6751e-03,  ..., 7.3344e-03,
          3.9435e-04, 5.8272e-05],
         [4.6682e-01, 4.5567e-01, 5.6185e-02,  ..., 3.5059e-03,
          9.7021e-05, 5.4564e-04],
         [9.3802e-01, 1.7568e-02, 3.3743e-02,  ..., 2.2006e-04,
          7.8713e-06, 5.1668e-04],
         ...,
         [8.7057e-01, 1.1468e-02, 5.5698e-03,  ..., 9.2428e-02,
          2.6278e-03, 1.3152e-04],
         [9.5173e-01, 5.6346e-03, 3.7540e-03,  ..., 2.9426e-02,
          9.5155e-04, 7.7219e-05],
         [9.3856e-01, 1.0057e-02, 5.2283e-03,  ..., 3.0682e-02,
          1.2352e-03, 1.4072e-04]],

        [[9.9652e-01, 6.0835e-04, 1.3176e-03,  ..., 2.8376e-04,
          8.8270e-05, 1.9299e-05],
         [2.9704e-01, 2.0263e-02, 6.2441e-01,  ..., 2.7057e-03,
          4.5876e-04, 8.3205e-04],
         [1.7129e-01, 9.5909e-03, 7.8783e-01,  ..., 3.5000e-04,
          8.2313e-05, 1.3321e-03],
         ...,
         [9.8854e-01, 1.5098e-03, 5.4006e-03,  ..., 9

tensor([[[9.9873e-01, 3.7761e-04, 8.3833e-05,  ..., 2.5441e-04,
          3.1819e-05, 1.1587e-05],
         [5.4568e-01, 1.3711e-02, 3.7861e-01,  ..., 8.5399e-04,
          1.7585e-04, 3.9293e-02],
         [1.7440e-01, 2.2094e-03, 6.4377e-01,  ..., 6.7147e-04,
          1.4384e-04, 1.3543e-01],
         ...,
         [8.7902e-01, 2.4139e-02, 5.8584e-03,  ..., 4.0481e-02,
          6.4163e-04, 4.1739e-04],
         [1.0573e-01, 1.8356e-02, 3.3535e-01,  ..., 1.0398e-01,
          1.2470e-03, 3.7045e-02],
         [6.5390e-01, 2.9127e-02, 1.7684e-02,  ..., 1.1157e-01,
          2.1120e-03, 2.0086e-03]],

        [[9.9868e-01, 3.8232e-04, 1.7396e-04,  ..., 7.7140e-05,
          2.5201e-05, 1.1615e-05],
         [9.3251e-01, 1.2597e-03, 1.5524e-04,  ..., 1.4220e-04,
          2.6369e-05, 9.0436e-06],
         [1.3804e-02, 1.2559e-04, 1.0781e-05,  ..., 2.7105e-05,
          5.8458e-06, 1.4305e-06],
         ...,
         [9.9837e-01, 6.2893e-04, 2.7452e-04,  ..., 6.8906e-05,
          4.634

batch_preds torch.Size([32, 128]) tensor([[0, 0, 2,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 3, 0, 3],
        [0, 0, 0,  ..., 8, 0, 0],
        [0, 1, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[8.9511e-01, 8.1094e-02, 1.8967e-03,  ..., 9.1885e-04,
          1.8671e-04, 1.2560e-04],
         [2.0018e-02, 9.6382e-01, 2.6113e-03,  ..., 1.4736e-04,
          5.0373e-05, 3.5159e-04],
         [7.7843e-01, 1.6074e-01, 9.7782e-03,  ..., 1.2033e-04,
          9.4773e-05, 2.4821e-03],
         ...,
         [3.5598e-01, 5.3871e-01, 1.6895e-02,  ..., 3.9197e-03,
          8.1120e-04, 5.1743e-04],
         [4.5657e-01, 3.9583e-01, 3.1395e-02,  ..., 4.5861e-03,
          9.2851e-04, 1.0177e-03],
         [2.0011e-01, 6.3778e-01, 4.6469e-03,  ..., 2.0870e-03,
          2.3254e-04, 1.8218e-04]],

        [[9.7728e-01, 7.7805e-03, 3.5611e-03,  ..., 6.6005e-04,
          1.4332e-04, 2.8698e-0

batch_preds torch.Size([32, 128]) tensor([[0, 1, 0,  ..., 1, 0, 1],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.7932e-01, 3.3660e-03, 6.4478e-04,  ..., 3.9507e-04,
          7.9973e-05, 3.0926e-04],
         [7.5336e-01, 1.4472e-01, 1.1195e-02,  ..., 1.6427e-03,
          5.3834e-04, 1.8684e-03],
         [9.8584e-01, 5.2789e-03, 5.6374e-04,  ..., 1.7927e-04,
          6.5630e-05, 2.0468e-04],
         ...,
         [1.0886e-01, 2.6989e-02, 2.2022e-02,  ..., 5.8695e-04,
          7.8915e-05, 6.9488e-03],
         [1.1114e-01, 2.4978e-02, 2.0269e-02,  ..., 5.4575e-04,
          7.2711e-05, 6.4928e-03],
         [3.4987e-02, 1.2727e-02, 1.1249e-02,  ..., 2.0768e-04,
          3.7175e-05, 3.2958e-03]],

        [[9.9231e-01, 2.1263e-03, 9.0107e-04,  ..., 5.7368e-04,
          9.3988e-05, 3.7122e-0

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 3, 3, 3],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 9,  ..., 0, 0, 0],
        [0, 0, 9,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9861e-01, 3.4138e-04, 1.5068e-04,  ..., 2.3187e-04,
          5.8010e-05, 5.3886e-06],
         [9.8398e-01, 2.6788e-04, 3.3755e-04,  ..., 1.0468e-04,
          1.4593e-05, 1.9835e-05],
         [5.4702e-03, 8.8444e-06, 3.4044e-05,  ..., 2.2482e-03,
          6.9894e-06, 2.3050e-06],
         ...,
         [9.8533e-01, 3.9029e-03, 1.9283e-03,  ..., 4.9383e-03,
          1.7210e-04, 4.2268e-05],
         [9.7559e-01, 5.5158e-03, 2.7888e-03,  ..., 9.9538e-03,
          3.0960e-04, 5.6691e-05],
         [3.0758e-01, 2.7011e-02, 1.3463e-01,  ..., 3.3790e-02,
          2.2457e-03, 6.5031e-03]],

        [[9.9562e-01, 9.1889e-04, 1.1155e-04,  ..., 2.3310e-04,
          7.6920e-05, 4.8223e-0

batch_preds torch.Size([32, 128]) tensor([[0, 0, 9,  ..., 0, 0, 6],
        [0, 0, 9,  ..., 0, 0, 0],
        [0, 2, 2,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 2, 2, 2]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9502e-01, 1.7642e-03, 6.4831e-04,  ..., 1.3586e-04,
          1.0041e-04, 2.3483e-04],
         [9.9865e-01, 2.9297e-04, 3.8401e-04,  ..., 3.1616e-05,
          6.7229e-05, 5.3454e-05],
         [9.9626e-01, 9.5436e-04, 1.4052e-03,  ..., 3.5903e-05,
          1.2596e-05, 1.3361e-04],
         ...,
         [9.9078e-01, 2.6973e-03, 1.7486e-03,  ..., 2.5822e-04,
          1.2125e-04, 2.4865e-04],
         [9.9112e-01, 2.7655e-03, 1.6717e-03,  ..., 2.2417e-04,
          1.1398e-04, 2.3871e-04],
         [6.7439e-02, 3.4517e-03, 1.3413e-02,  ..., 3.3219e-04,
          1.7383e-04, 1.5816e-02]],

        [[9.9793e-01, 4.4027e-04, 5.1086e-04,  ..., 2.1143e-04,
          4.1547e-05, 1.2171e-0

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 4],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 1],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 3]], device='cuda:0')
torch.Size([32, 128, 16])


tensor([[[9.6904e-01, 1.2637e-02, 5.6045e-04,  ..., 6.0055e-03,
          1.1318e-04, 7.5168e-05],
         [9.9437e-01, 2.2869e-03, 1.6509e-04,  ..., 2.9103e-04,
          1.6003e-04, 3.6182e-05],
         [9.6213e-01, 1.0884e-02, 1.9393e-04,  ..., 5.5233e-03,
          2.1023e-04, 4.4481e-05],
         ...,
         [7.7334e-01, 9.4397e-02, 1.4545e-02,  ..., 3.4213e-02,
          2.1940e-04, 4.8515e-04],
         [7.1930e-01, 1.5948e-01, 1.2464e-02,  ..., 2.1248e-02,
          3.0554e-04, 7.8171e-04],
         [7.0617e-01, 2.1584e-01, 8.5104e-03,  ..., 8.5301e-03,
          4.0983e-04, 8.2913e-04]],

        [[9.9048e-01, 1.8612e-03, 1.1533e-03,  ..., 4.1984e-04,
          7.0096e-05, 2.6349e-04],
         [7.7747e-01, 2.5174e-03, 1.4066e-03,  ..., 5.7457e-04,
          1.1398e-04, 3.1152e-04],
         [2.3966e-01, 6.3275e-04, 5.6453e-04,  ..., 5.8020e-04,
          2.0611e-04, 2.6229e-04],
         ...,
         [2.4730e-01, 9.6594e-02, 3.5113e-01,  ..., 2.4327e-03,
          4.134

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0],
        ...,
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.7766e-01, 6.4079e-03, 3.1139e-03,  ..., 1.0252e-03,
          2.8155e-04, 1.5195e-04],
         [5.8732e-01, 2.5960e-01, 7.3389e-02,  ..., 2.6997e-03,
          1.9484e-03, 1.7106e-03],
         [4.9692e-01, 2.6843e-01, 9.5813e-02,  ..., 4.2947e-03,
          2.1649e-03, 1.6704e-03],
         ...,
         [9.5767e-01, 1.2242e-02, 9.1494e-03,  ..., 1.6210e-03,
          6.7016e-04, 4.5764e-04],
         [9.3931e-01, 1.7897e-02, 1.3100e-02,  ..., 2.0301e-03,
          8.3682e-04, 6.6231e-04],
         [8.2071e-01, 2.8194e-02, 3.4670e-02,  ..., 3.1031e-03,
          7.5580e-04, 1.1624e-03]],

        [[9.9897e-01, 2.6318e-04, 1.0896e-04,  ..., 1.0537e-04,
          8.3101e-05, 2.7005e-0

batch_preds torch.Size([32, 128]) tensor([[ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  9,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        ...,
        [ 0,  1,  1,  ...,  0,  0,  0],
        [ 0,  0, 13,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  1]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.7960e-01, 9.5192e-03, 6.2159e-04,  ..., 5.1612e-04,
          1.1932e-04, 6.8955e-05],
         [3.7474e-01, 5.5558e-01, 1.3279e-02,  ..., 1.6970e-03,
          4.0972e-04, 4.8556e-04],
         [9.9190e-01, 5.7338e-03, 9.7929e-05,  ..., 5.3714e-04,
          1.2987e-04, 1.0786e-05],
         ...,
         [8.2370e-01, 1.0772e-01, 8.7051e-03,  ..., 3.1968e-03,
          4.7131e-04, 6.1574e-04],
         [8.2146e-01, 1.1390e-01, 8.2700e-03,  ..., 3.0229e-03,
          4.1939e-04, 6.1202e-04],
         [3.1053e-01, 6.1587e-01, 1.2541e-02,  ..., 2.6481e-03,
          6.3044e-04, 7.4048e-04]],

        [[9.9360e-01, 8.5144e-04, 1.0023e-03,  ..., 3.5273e


batch_preds torch.Size([32, 128]) tensor([[0, 1, 0,  ..., 0, 0, 1],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9679e-01, 9.4572e-04, 5.3678e-04,  ..., 1.5972e-04,
          1.1239e-04, 3.7610e-05],
         [7.4263e-01, 3.1624e-02, 1.7266e-03,  ..., 7.2284e-04,
          1.9579e-03, 2.5190e-04],
         [2.5794e-01, 2.3878e-03, 1.0170e-03,  ..., 5.2322e-04,
          1.3775e-03, 1.0592e-04],
         ...,
         [9.9080e-01, 2.7797e-03, 2.2535e-03,  ..., 6.9808e-04,
          2.2344e-04, 1.1451e-04],
         [9.8539e-01, 4.6653e-03, 3.7781e-03,  ..., 7.7381e-04,
          2.4073e-04, 1.6110e-04],
         [9.7555e-01, 5.7663e-03, 4.0767e-03,  ..., 1.2061e-03,
          3.7528e-04, 2.1498e-04]],

        [[9.9702e-01, 7.1972e-04, 3.8006e-04,  ..., 5.3877e-04,
          1.6118e-04, 3.2068e-

batch_preds torch.Size([32, 128]) tensor([[ 0,  0,  9,  ...,  0,  0,  0],
        [ 0,  0, 14,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        ...,
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  9,  ...,  0,  0,  0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9635e-01, 7.6321e-04, 2.6448e-04,  ..., 1.2417e-03,
          8.9226e-05, 1.5977e-05],
         [9.9024e-01, 8.4791e-04, 3.2753e-04,  ..., 3.0651e-04,
          1.5875e-04, 1.7429e-05],
         [9.5113e-01, 3.4623e-03, 1.4764e-03,  ..., 6.6371e-04,
          2.6528e-04, 2.9748e-05],
         ...,
         [9.9148e-01, 2.0088e-03, 6.9527e-04,  ..., 3.5208e-03,
          1.6177e-04, 2.2722e-05],
         [9.9516e-01, 1.0579e-03, 5.1144e-04,  ..., 1.7407e-03,
          1.2439e-04, 2.0635e-05],
         [9.9025e-01, 3.0790e-03, 6.0069e-04,  ..., 3.2977e-03,
          2.2788e-04, 1.9609e-05]],

        [[9.9921e-01, 1.7278e-04, 1.5620e-04,  ..., 1.1040e

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 3],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9603e-01, 1.6488e-03, 3.1154e-04,  ..., 2.3702e-04,
          1.7919e-04, 5.6848e-05],
         [9.8733e-01, 4.9985e-03, 2.0189e-03,  ..., 2.0972e-03,
          5.4321e-04, 7.6332e-05],
         [9.9637e-01, 1.2272e-03, 6.0566e-04,  ..., 4.1655e-04,
          3.7761e-05, 1.4465e-05],
         ...,
         [1.9903e-01, 2.0086e-02, 6.7423e-02,  ..., 1.2833e-03,
          1.2320e-04, 1.0860e-01],
         [6.2288e-01, 3.3327e-02, 5.1888e-02,  ..., 3.2711e-03,
          4.8926e-04, 2.9470e-02],
         [1.8224e-01, 1.7927e-02, 5.7517e-02,  ..., 1.2176e-03,
          1.0517e-04, 8.1157e-02]],

        [[9.8438e-01, 1.0824e-02, 1.6047e-03,  ..., 1.4182e-04,
          6.1969e-05, 4.9329e-0


batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 3, 0, 3],
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 3],
        ...,
        [0, 0, 1,  ..., 0, 2, 2],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9155e-01, 2.3808e-03, 6.7305e-04,  ..., 5.6207e-04,
          5.9434e-05, 5.6277e-05],
         [9.2949e-01, 2.5176e-02, 1.4835e-02,  ..., 2.4567e-03,
          1.0733e-03, 5.7299e-04],
         [9.8288e-01, 3.1140e-03, 1.7641e-03,  ..., 3.6424e-03,
          2.5213e-04, 1.0644e-04],
         ...,
         [9.8571e-01, 5.6563e-03, 1.8943e-03,  ..., 1.4916e-03,
          1.1887e-04, 1.4889e-04],
         [9.3756e-01, 1.6921e-02, 1.6794e-02,  ..., 4.7091e-03,
          3.0919e-04, 7.6813e-04],
         [8.8881e-01, 2.7369e-02, 3.1094e-02,  ..., 6.3813e-03,
          2.8434e-04, 1.0555e-03]],

        [[9.9693e-01, 5.6334e-04, 6.4103e-04,  ..., 1.1472e-04,
          1.4072e-04, 2.0482e-

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 2,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])


tensor([[[9.9784e-01, 4.3427e-04, 1.1838e-04,  ..., 3.0805e-04,
          1.5009e-04, 8.5971e-06],
         [9.8502e-01, 3.9606e-04, 7.9476e-05,  ..., 1.8938e-05,
          8.0373e-05, 3.2629e-05],
         [6.3275e-01, 3.1975e-04, 9.3567e-05,  ..., 1.4266e-04,
          7.0679e-04, 7.8299e-05],
         ...,
         [1.3033e-01, 6.9689e-01, 6.5214e-02,  ..., 7.5856e-03,
          7.7658e-04, 2.0735e-03],
         [1.8592e-01, 6.1127e-01, 7.0991e-02,  ..., 8.9265e-03,
          9.1929e-04, 2.2143e-03],
         [1.7518e-01, 6.3842e-01, 6.4947e-02,  ..., 6.6947e-03,
          8.8118e-04, 2.0652e-03]],

        [[9.9736e-01, 2.3911e-04, 1.9701e-04,  ..., 6.1649e-04,
          1.3121e-04, 8.0925e-06],
         [8.5586e-02, 8.4131e-01, 2.8594e-02,  ..., 1.6716e-04,
          1.0844e-04, 2.0221e-04],
         [6.5684e-03, 7.6969e-03, 1.6728e-03,  ..., 2.0989e-05,
          1.6122e-06, 1.2742e-05],
         ...,
         [9.9378e-01, 9.3297e-04, 6.3170e-04,  ..., 1.8427e-03,
          1.357


batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 9,  ..., 0, 1, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9459e-01, 3.5910e-03, 2.0273e-04,  ..., 1.6183e-04,
          7.5748e-05, 2.0936e-05],
         [9.9345e-01, 1.3059e-03, 5.1405e-05,  ..., 1.8103e-05,
          1.4300e-05, 1.1758e-05],
         [4.9221e-02, 2.2882e-04, 3.2532e-05,  ..., 5.2070e-05,
          3.7281e-05, 8.4161e-06],
         ...,
         [9.8718e-01, 7.2815e-03, 6.3871e-04,  ..., 1.2815e-03,
          1.8643e-04, 9.0919e-05],
         [4.5151e-01, 5.0722e-01, 9.9453e-03,  ..., 2.7225e-03,
          1.1109e-03, 1.9711e-04],
         [5.4620e-01, 3.9387e-01, 1.0695e-02,  ..., 3.6923e-03,
          2.0313e-03, 1.7254e-04]],

        [[9.9679e-01, 1.1124e-03, 7.5199e-05,  ..., 3.9480e-04,
          1.1049e-04, 1.1065e-


batch_preds torch.Size([32, 128]) tensor([[0, 0, 9,  ..., 0, 1, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9610e-01, 1.1077e-03, 2.8811e-04,  ..., 2.5303e-04,
          7.1794e-05, 5.8003e-05],
         [7.5840e-01, 1.5784e-01, 2.8580e-02,  ..., 1.5856e-03,
          3.8301e-04, 7.0330e-04],
         [9.9673e-01, 1.1766e-03, 1.0315e-03,  ..., 1.8576e-05,
          2.9327e-05, 5.5935e-05],
         ...,
         [9.8604e-01, 7.8643e-03, 4.8327e-04,  ..., 1.0672e-04,
          4.3907e-05, 6.0674e-05],
         [9.8477e-01, 7.7557e-03, 5.5266e-04,  ..., 1.4204e-04,
          6.3908e-05, 7.5003e-05],
         [9.8852e-01, 6.2475e-03, 3.8906e-04,  ..., 9.9014e-05,
          3.1609e-05, 4.3075e-05]],

        [[9.9744e-01, 7.0931e-04, 1.6325e-04,  ..., 6.3518e-05,
          4.3435e-05, 1.9793e-

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 1],
        [0, 0, 2,  ..., 0, 0, 0],
        ...,
        [0, 0, 9,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9681e-01, 5.6675e-04, 5.0052e-04,  ..., 2.1740e-04,
          1.0062e-04, 5.0807e-05],
         [9.9884e-01, 1.1537e-04, 1.2630e-04,  ..., 1.7007e-04,
          4.9498e-05, 9.8042e-06],
         [9.7280e-01, 2.5797e-03, 3.9345e-03,  ..., 1.0753e-03,
          4.5570e-03, 1.9181e-03],
         ...,
         [9.8947e-01, 2.0800e-03, 2.0332e-03,  ..., 1.4058e-03,
          3.2441e-04, 1.3029e-04],
         [9.9342e-01, 1.3248e-03, 1.1737e-03,  ..., 9.0456e-04,
          2.5305e-04, 9.3651e-05],
         [9.8220e-01, 3.5581e-03, 4.3160e-03,  ..., 1.9964e-03,
          4.4517e-04, 3.8776e-04]],

        [[9.9851e-01, 4.4280e-04, 8.1791e-05,  ..., 1.8111e-04,
          5.8607e-05, 7.0908e-0


batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 3,  ..., 0, 0, 1],
        [0, 0, 0,  ..., 3, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9453e-01, 1.6180e-03, 6.6005e-04,  ..., 4.9285e-04,
          8.8435e-05, 3.8650e-05],
         [8.9103e-01, 2.2172e-03, 1.4099e-03,  ..., 2.3583e-04,
          3.2331e-05, 9.7303e-05],
         [6.8776e-01, 3.7580e-04, 6.4383e-04,  ..., 3.1329e-05,
          1.3665e-05, 1.4121e-04],
         ...,
         [9.5693e-01, 2.2427e-02, 7.9414e-03,  ..., 2.3022e-03,
          2.7866e-04, 2.9260e-04],
         [9.7364e-01, 8.4919e-03, 6.1140e-03,  ..., 2.0997e-03,
          2.0177e-04, 2.6308e-04],
         [9.2847e-01, 1.6770e-02, 1.6953e-02,  ..., 5.6512e-03,
          3.0390e-04, 8.1231e-04]],

        [[9.8621e-01, 3.4772e-03, 8.0611e-04,  ..., 7.2171e-04,
          8.0856e-05, 7.6909e-

tensor([[ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  1,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        ...,
        [ 0,  0, 14,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  5,  5,  0],
        [ 0,  0,  0,  ...,  0,  0,  9]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9773e-01, 8.0488e-04, 1.4081e-04,  ..., 1.9009e-04,
          2.2280e-05, 2.0690e-05],
         [9.8299e-01, 7.6636e-04, 7.9917e-05,  ..., 4.0268e-05,
          3.2916e-06, 2.9797e-05],
         [2.9203e-03, 7.9432e-06, 8.4426e-06,  ..., 4.0549e-04,
          1.7038e-06, 1.8722e-06],
         ...,
         [9.9309e-01, 2.4803e-03, 1.0187e-03,  ..., 6.4727e-04,
          3.9960e-05, 8.6124e-05],
         [9.9032e-01, 3.2017e-03, 1.5080e-03,  ..., 9.3356e-04,
          4.3270e-05, 1.2017e-04],
         [9.3698e-01, 3.1903e-02, 7.0584e-03,  ..., 5.1776e-03,
          1.9800e-04, 5.4046e-04]],

        [[9.9322e-01, 2.0852e-03, 3.8240e-04,  ..., 5.7533e-04,
          2.4929e-04, 8.8176e

torch.Size([32, 128, 16])
tensor([[[9.9835e-01, 4.7564e-04, 2.0083e-04,  ..., 1.7878e-04,
          2.0115e-05, 6.1480e-05],
         [9.9187e-01, 6.3339e-04, 4.2410e-05,  ..., 3.0246e-05,
          1.6442e-05, 1.7804e-05],
         [3.0157e-01, 5.9203e-04, 1.4383e-04,  ..., 6.4821e-05,
          8.8173e-05, 3.9469e-05],
         ...,
         [9.9799e-01, 5.5382e-04, 3.1360e-04,  ..., 1.3632e-04,
          5.5405e-05, 6.1725e-05],
         [9.9787e-01, 6.0267e-04, 3.1673e-04,  ..., 1.4249e-04,
          4.9009e-05, 6.2897e-05],
         [9.9800e-01, 6.7798e-04, 2.9672e-04,  ..., 1.2293e-04,
          4.5934e-05, 6.3551e-05]],

        [[9.9460e-01, 5.2092e-04, 1.9277e-04,  ..., 8.8895e-04,
          6.1626e-04, 3.3988e-05],
         [9.6469e-01, 2.1444e-03, 8.8778e-04,  ..., 7.1751e-04,
          4.3769e-05, 1.5707e-04],
         [9.2494e-01, 3.9619e-04, 5.8758e-04,  ..., 6.0424e-05,
          5.9472e-05, 2.1385e-04],
         ...,
         [9.6887e-01, 1.1928e-03, 6.1557e-04,  ..., 8

tensor([[[9.9608e-01, 5.6429e-04, 1.7069e-03,  ..., 1.0368e-04,
          1.6516e-05, 4.3431e-05],
         [9.9910e-01, 6.7830e-05, 1.1371e-04,  ..., 1.4675e-05,
          3.8693e-05, 1.1143e-05],
         [9.9434e-01, 4.6502e-05, 1.1207e-04,  ..., 3.7512e-05,
          2.6427e-04, 5.6251e-05],
         ...,
         [6.3051e-01, 2.8272e-02, 2.3501e-01,  ..., 9.0609e-04,
          5.6504e-05, 1.8053e-03],
         [9.5227e-01, 3.7120e-03, 2.6423e-02,  ..., 5.1857e-04,
          3.0401e-05, 3.9193e-04],
         [9.7105e-01, 6.2354e-03, 1.2017e-02,  ..., 2.6917e-04,
          9.1348e-06, 1.5803e-04]],

        [[9.9202e-01, 3.0878e-03, 7.0748e-04,  ..., 3.9160e-04,
          9.0860e-05, 2.9544e-05],
         [4.2534e-01, 5.4414e-01, 1.7628e-02,  ..., 3.6293e-04,
          2.5004e-04, 5.0032e-04],
         [1.3218e-01, 7.1271e-01, 1.1454e-01,  ..., 8.3540e-04,
          2.7292e-04, 2.1538e-03],
         ...,
         [9.8529e-01, 5.5895e-03, 1.2858e-03,  ..., 1.0319e-03,
          1.781

batch_preds torch.Size([32, 128]) tensor([[0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 1, 2,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 9,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9671e-01, 1.3227e-03, 4.9442e-04,  ..., 1.7760e-04,
          1.3144e-04, 2.1725e-05],
         [2.0729e-01, 7.8320e-01, 6.0606e-03,  ..., 1.6706e-04,
          6.9521e-04, 2.1571e-04],
         [4.5061e-01, 1.5946e-01, 3.5511e-01,  ..., 8.1499e-04,
          1.0733e-03, 4.3917e-03],
         ...,
         [9.8626e-01, 5.3789e-03, 2.6690e-03,  ..., 8.6150e-04,
          3.8388e-04, 1.2227e-04],
         [9.8868e-01, 4.8153e-03, 2.0493e-03,  ..., 6.1070e-04,
          3.4949e-04, 9.6652e-05],
         [9.8505e-01, 8.2423e-03, 1.7728e-03,  ..., 3.7667e-04,
          2.7943e-04, 6.5871e-05]],

        [[9.9235e-01, 3.3665e-03, 7.0487e-04,  ..., 2.0229e-04,
          2.8532e-05, 5.7277e-0

batch_preds torch.Size([32, 128]) tensor([[0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 1],
        [0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9835e-01, 4.4598e-04, 3.4149e-04,  ..., 1.9025e-04,
          2.9498e-05, 1.3888e-05],
         [9.9247e-01, 2.4300e-04, 5.0842e-05,  ..., 9.1162e-05,
          1.1079e-05, 4.2259e-06],
         [9.5555e-02, 3.2768e-04, 2.9357e-05,  ..., 2.7025e-05,
          8.4857e-06, 9.7893e-06],
         ...,
         [9.8057e-01, 5.3657e-03, 6.1450e-03,  ..., 1.6599e-03,
          2.0229e-04, 1.5955e-04],
         [9.8229e-01, 5.1607e-03, 5.2263e-03,  ..., 1.1567e-03,
          1.3134e-04, 1.4848e-04],
         [9.8123e-01, 6.7200e-03, 4.6758e-03,  ..., 1.6764e-03,
          1.6170e-04, 1.6719e-04]],

        [[9.9263e-01, 8.9224e-04, 3.7299e-04,  ..., 4.4093e-04,
          2.1839e-04, 9.0194e-0

batch_preds torch.Size([32, 128]) tensor([[0, 0, 9,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 2, 2],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 2, 2,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.6385e-01, 7.5194e-03, 1.9055e-03,  ..., 6.1046e-03,
          2.2061e-04, 1.9334e-04],
         [3.9714e-02, 9.5338e-01, 1.7468e-03,  ..., 1.7119e-04,
          1.8886e-04, 6.2447e-04],
         [5.0062e-01, 2.8953e-01, 8.7272e-02,  ..., 1.0593e-03,
          1.6159e-03, 5.3114e-02],
         ...,
         [9.6627e-01, 1.0139e-02, 3.1191e-03,  ..., 2.4601e-03,
          3.4170e-04, 1.4581e-04],
         [9.6254e-01, 1.1401e-02, 3.3427e-03,  ..., 2.4300e-03,
          3.6076e-04, 1.7563e-04],
         [9.6975e-01, 8.0564e-03, 2.6080e-03,  ..., 2.0352e-03,
          3.0610e-04, 1.3536e-04]],

        [[9.9716e-01, 5.2943e-04, 7.5603e-04,  ..., 1.4287e-04,
          4.8286e-05, 3.7875e-0

batch_preds torch.Size([32, 128]) tensor([[ 0,  1,  0,  ...,  0,  0,  0],
        [ 0,  0,  9,  ...,  0,  0,  0],
        [ 0,  0,  9,  ...,  0,  0,  0],
        ...,
        [ 0,  0, 14,  ...,  1,  1,  1],
        [ 0,  2,  2,  ...,  0,  0,  0],
        [ 0,  1,  1,  ...,  0,  0,  2]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9588e-01, 1.2338e-03, 5.8569e-04,  ..., 2.3359e-04,
          6.5858e-05, 8.5134e-05],
         [8.4234e-01, 4.3157e-02, 5.1564e-02,  ..., 1.4168e-03,
          4.4045e-04, 3.0558e-03],
         [9.9704e-01, 6.6934e-04, 1.0448e-03,  ..., 6.4892e-05,
          6.7774e-05, 1.1552e-04],
         ...,
         [9.8541e-01, 5.7998e-03, 2.6182e-03,  ..., 9.6523e-04,
          1.6027e-04, 2.0405e-04],
         [9.8212e-01, 7.0635e-03, 3.5714e-03,  ..., 1.2932e-03,
          1.5979e-04, 2.7879e-04],
         [9.5182e-01, 2.0011e-02, 1.0936e-02,  ..., 2.2206e-03,
          3.8623e-04, 8.3978e-04]],

        [[9.9280e-01, 1.0565e-03, 7.2600e-04,  ..., 2.3441e

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 9, 0, 0],
        ...,
        [0, 0, 9,  ..., 0, 0, 0],
        [0, 2, 2,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9481e-01, 6.9005e-04, 1.0819e-03,  ..., 1.3690e-04,
          1.0783e-04, 1.2443e-04],
         [9.8164e-01, 1.5281e-03, 3.2846e-03,  ..., 3.4338e-04,
          8.3886e-04, 3.6969e-04],
         [9.8059e-01, 9.0724e-04, 1.5872e-03,  ..., 7.4516e-04,
          4.4114e-04, 2.8039e-04],
         ...,
         [6.1767e-01, 6.9007e-03, 3.8464e-02,  ..., 3.5123e-03,
          5.1477e-04, 7.5020e-03],
         [5.1346e-01, 4.9025e-03, 2.3416e-02,  ..., 1.0087e-03,
          2.3507e-04, 7.5226e-03],
         [6.4736e-02, 2.1809e-03, 6.6226e-03,  ..., 4.4220e-04,
          7.9123e-05, 6.3321e-03]],

        [[9.9139e-01, 9.6022e-04, 1.8339e-04,  ..., 4.1383e-04,
          7.2804e-05, 3.0767e-0


batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 4],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 1, 1,  ..., 0, 0, 1],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9627e-01, 5.3729e-04, 1.5077e-03,  ..., 3.3015e-04,
          2.8101e-05, 6.6347e-05],
         [8.7265e-01, 2.6585e-02, 5.3069e-02,  ..., 4.4991e-03,
          1.1443e-04, 6.3602e-04],
         [9.9762e-01, 3.9655e-04, 1.3681e-03,  ..., 2.0741e-04,
          1.0705e-05, 4.0392e-05],
         ...,
         [5.7365e-01, 5.2978e-03, 4.6808e-03,  ..., 2.7368e-02,
          4.2900e-04, 3.4828e-04],
         [9.4889e-01, 2.6210e-03, 2.2197e-02,  ..., 7.4332e-03,
          1.6659e-04, 4.3392e-04],
         [9.7987e-01, 1.9944e-03, 7.7962e-03,  ..., 2.2308e-03,
          1.9636e-04, 2.3138e-04]],

        [[9.9527e-01, 1.5105e-03, 1.3017e-04,  ..., 2.6988e-04,
          1.2956e-04, 1.8605e-

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 9,  ..., 0, 0, 1],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 3,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 5,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9810e-01, 4.1741e-04, 3.3745e-04,  ..., 2.2362e-04,
          6.9929e-05, 1.2448e-05],
         [9.8614e-01, 1.8942e-03, 3.1768e-03,  ..., 1.2693e-03,
          6.4922e-04, 1.0100e-04],
         [9.9909e-01, 1.1397e-04, 2.3335e-04,  ..., 7.8461e-05,
          1.4536e-05, 2.0810e-05],
         ...,
         [9.8390e-01, 3.5549e-03, 3.0903e-03,  ..., 1.1329e-03,
          1.0661e-04, 7.7114e-05],
         [9.8215e-01, 5.7057e-03, 3.3601e-03,  ..., 1.1099e-03,
          1.1626e-04, 7.5257e-05],
         [9.4183e-01, 4.0323e-02, 5.0997e-03,  ..., 1.9681e-03,
          1.7693e-04, 9.3266e-05]],

        [[9.8196e-01, 2.7962e-03, 3.5715e-04,  ..., 4.3737e-04,
          1.3419e-04, 6.5489e-0

batch_preds torch.Size([32, 128]) tensor([[ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0, 13,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        ...,
        [ 0,  0,  0,  ...,  2,  2,  2],
        [ 0,  2,  2,  ...,  0,  0,  2],
        [ 0,  0,  0,  ...,  0,  0,  0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9442e-01, 2.9966e-03, 2.5719e-04,  ..., 4.2699e-04,
          6.4404e-05, 2.1364e-05],
         [1.9490e-01, 7.8680e-01, 1.6689e-03,  ..., 1.4052e-03,
          4.2355e-03, 2.2462e-04],
         [6.8211e-01, 2.5930e-01, 2.4575e-03,  ..., 2.1976e-03,
          1.3161e-03, 2.1800e-04],
         ...,
         [9.7026e-01, 1.8375e-02, 1.7413e-03,  ..., 1.5365e-03,
          1.6212e-04, 1.1691e-04],
         [9.7496e-01, 1.5892e-02, 1.3596e-03,  ..., 1.2590e-03,
          1.5016e-04, 9.3639e-05],
         [9.7666e-01, 1.5539e-02, 1.1454e-03,  ..., 1.0060e-03,
          1.1049e-04, 4.4009e-05]],

        [[9.9674e-01, 4.2451e-04, 6.9232e-04,  ..., 7.2782e


batch_preds torch.Size([32, 128]) tensor([[0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 2],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9591e-01, 8.3763e-04, 3.4370e-04,  ..., 2.9513e-04,
          1.0286e-04, 2.4957e-05],
         [9.6003e-01, 7.9169e-03, 1.2230e-03,  ..., 9.6507e-04,
          2.9272e-04, 1.3710e-04],
         [9.8101e-01, 1.5794e-03, 1.2971e-03,  ..., 1.5188e-04,
          5.5926e-04, 2.2958e-04],
         ...,
         [9.8523e-01, 4.0223e-03, 1.9676e-03,  ..., 1.8329e-03,
          3.0222e-04, 1.0250e-04],
         [9.7338e-01, 7.5122e-03, 4.3280e-03,  ..., 3.3154e-03,
          3.8641e-04, 1.9761e-04],
         [4.5579e-01, 1.4112e-01, 1.3994e-01,  ..., 2.4216e-02,
          4.0600e-03, 7.0672e-03]],

        [[9.9806e-01, 8.4725e-04, 1.5589e-04,  ..., 8.1411e-05,
          6.9782e-05, 1.3709e-

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 1, 1,  ..., 0, 0, 2],
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])


tensor([[[9.9498e-01, 2.1270e-03, 6.1364e-04,  ..., 2.4272e-04,
          1.3039e-04, 2.2270e-05],
         [9.9718e-01, 2.4129e-04, 1.5502e-04,  ..., 2.6050e-05,
          7.3125e-05, 4.1300e-06],
         [9.9462e-01, 1.4592e-04, 1.5140e-04,  ..., 2.0247e-05,
          3.1571e-06, 5.6009e-06],
         ...,
         [9.3280e-01, 4.3038e-02, 1.0378e-02,  ..., 7.1789e-04,
          2.1089e-04, 1.6805e-04],
         [7.5642e-01, 1.7638e-01, 3.1350e-02,  ..., 1.2132e-03,
          2.7525e-04, 4.1720e-04],
         [6.5649e-01, 2.7810e-01, 3.2420e-02,  ..., 1.4040e-03,
          2.4977e-04, 4.2037e-04]],

        [[9.9529e-01, 8.5408e-04, 7.2458e-04,  ..., 1.9022e-04,
          8.0720e-05, 2.7630e-05],
         [9.5963e-01, 5.7417e-04, 8.4776e-04,  ..., 2.6356e-04,
          2.1967e-05, 4.4398e-05],
         [4.0142e-01, 1.6842e-03, 4.1704e-03,  ..., 2.1004e-04,
          1.2681e-05, 2.6047e-04],
         ...,
         [9.5042e-01, 2.3376e-02, 1.1443e-02,  ..., 7.6927e-04,
          2.071


batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 1, 1, 0],
        [0, 9, 9,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 4, 0, 4],
        [0, 0, 6,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9044e-01, 4.6462e-03, 9.0377e-04,  ..., 2.2831e-04,
          2.7113e-04, 7.8498e-05],
         [9.8675e-01, 5.5338e-03, 1.8487e-03,  ..., 1.0972e-04,
          4.6389e-04, 1.4157e-04],
         [8.7489e-01, 8.8021e-02, 9.9586e-03,  ..., 5.9211e-04,
          2.7934e-03, 5.8627e-04],
         ...,
         [9.8661e-01, 5.7372e-03, 2.9601e-03,  ..., 3.5170e-04,
          1.2375e-04, 1.5944e-04],
         [9.8926e-01, 4.4880e-03, 2.4670e-03,  ..., 2.8527e-04,
          1.1570e-04, 1.3656e-04],
         [9.3020e-01, 5.0070e-02, 6.3812e-03,  ..., 5.5890e-04,
          5.0667e-04, 3.7469e-04]],

        [[9.9716e-01, 6.9201e-04, 2.0167e-04,  ..., 1.7014e-04,
          2.0617e-04, 2.0147e-

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 6, 0, 6],
        ...,
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 2]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9651e-01, 8.1636e-04, 1.0282e-03,  ..., 1.8144e-04,
          3.2520e-05, 1.6816e-05],
         [1.6581e-01, 7.4000e-01, 8.0077e-02,  ..., 1.1406e-03,
          1.4812e-04, 5.5836e-04],
         [3.9840e-02, 8.6602e-01, 8.4675e-02,  ..., 6.4739e-04,
          8.9460e-05, 6.1285e-04],
         ...,
         [1.6054e-01, 2.6984e-02, 7.0884e-01,  ..., 1.0923e-03,
          1.6850e-04, 4.6306e-03],
         [1.6105e-01, 2.6071e-02, 7.2656e-01,  ..., 7.6901e-04,
          1.6220e-04, 4.4848e-03],
         [1.7203e-01, 2.4641e-02, 7.1397e-01,  ..., 8.6879e-04,
          2.2820e-04, 5.5013e-03]],

        [[9.9715e-01, 1.0950e-03, 8.1749e-05,  ..., 1.4426e-04,
          1.1632e-04, 1.4426e-0

batch_preds torch.Size([32, 128]) tensor([[0, 1, 1,  ..., 2, 2, 2],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 1, 1,  ..., 0, 0, 1],
        [0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9238e-01, 5.5805e-04, 1.3254e-03,  ..., 2.9825e-03,
          1.7646e-04, 2.0792e-05],
         [8.9077e-01, 4.0748e-02, 5.3130e-02,  ..., 1.8138e-03,
          4.7543e-04, 8.2043e-04],
         [8.2072e-01, 2.5031e-02, 9.1622e-02,  ..., 5.3879e-03,
          7.6816e-04, 1.7026e-03],
         ...,
         [9.7418e-01, 1.5014e-03, 4.6542e-03,  ..., 1.3419e-02,
          3.0208e-04, 5.5242e-05],
         [9.7759e-01, 1.2749e-03, 4.2383e-03,  ..., 1.1324e-02,
          2.7967e-04, 5.1695e-05],
         [9.7788e-01, 1.5971e-03, 3.9220e-03,  ..., 9.7748e-03,
          3.1862e-04, 5.5752e-05]],

        [[9.9550e-01, 1.0932e-03, 1.2640e-03,  ..., 5.0435e-04,
          1.4298e-04, 4.0903e-0

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9811e-01, 5.1994e-04, 5.4538e-05,  ..., 1.5536e-04,
          1.5359e-05, 2.9970e-05],
         [9.0239e-01, 9.4086e-03, 2.9036e-03,  ..., 3.8626e-04,
          6.7779e-05, 4.8922e-03],
         [1.2592e-01, 3.3872e-03, 1.7515e-02,  ..., 1.9036e-04,
          1.1458e-04, 3.0562e-02],
         ...,
         [9.6946e-01, 1.3591e-02, 6.3618e-04,  ..., 1.0592e-03,
          2.9961e-05, 2.8959e-04],
         [9.7415e-01, 8.0751e-03, 7.2381e-04,  ..., 6.2746e-04,
          2.5742e-05, 3.7936e-04],
         [9.8857e-01, 3.4055e-03, 9.1994e-05,  ..., 2.1834e-03,
          6.3568e-05, 9.8777e-05]],

        [[9.9266e-01, 1.1608e-03, 2.5305e-03,  ..., 3.8266e-04,
          1.1797e-04, 7.7561e-0

batch_preds torch.Size([32, 128]) tensor([[0, 0, 8,  ..., 0, 0, 0],
        [0, 2, 2,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 9,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9871e-01, 2.1201e-04, 1.6257e-04,  ..., 1.2732e-04,
          2.5658e-05, 7.1935e-06],
         [9.9914e-01, 6.1483e-05, 1.0433e-04,  ..., 6.5739e-05,
          1.2932e-04, 3.7104e-06],
         [9.9170e-01, 1.8918e-04, 1.4748e-04,  ..., 7.0548e-04,
          2.1779e-03, 1.3169e-05],
         ...,
         [5.3479e-02, 2.9189e-03, 3.5000e-02,  ..., 5.5332e-04,
          6.6283e-05, 3.7796e-03],
         [8.4356e-02, 3.5407e-03, 4.9040e-02,  ..., 8.0113e-04,
          9.0226e-05, 4.7913e-03],
         [5.9441e-02, 3.2088e-03, 3.6977e-02,  ..., 7.5002e-04,
          8.3847e-05, 3.9911e-03]],

        [[9.9289e-01, 3.2802e-03, 3.7799e-04,  ..., 4.6789e-04,
          3.3629e-04, 4.8598e-0

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 3, 3, 3],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 2],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])


tensor([[[9.8352e-01, 1.4485e-03, 4.2795e-03,  ..., 8.6857e-04,
          3.9803e-04, 5.7769e-04],
         [6.3952e-01, 1.6313e-02, 2.8775e-02,  ..., 8.5698e-03,
          1.9754e-03, 5.2940e-03],
         [9.5632e-01, 9.1713e-04, 2.6122e-03,  ..., 7.9727e-04,
          2.7204e-04, 7.7073e-04],
         ...,
         [7.8833e-01, 1.9968e-02, 1.1946e-01,  ..., 6.4616e-03,
          1.3524e-03, 8.0221e-03],
         [8.1681e-01, 1.5712e-02, 1.0031e-01,  ..., 6.1149e-03,
          1.1830e-03, 6.6277e-03],
         [8.5508e-01, 2.3107e-02, 5.5618e-02,  ..., 3.1626e-03,
          1.4087e-03, 3.4530e-03]],

        [[9.9813e-01, 9.0077e-04, 3.1645e-04,  ..., 1.5417e-04,
          1.5041e-05, 6.3578e-06],
         [9.8757e-01, 9.9234e-03, 5.1121e-04,  ..., 3.2338e-04,
          2.5607e-04, 4.4943e-05],
         [9.9887e-01, 3.8585e-04, 2.0260e-04,  ..., 7.5514e-05,
          6.3036e-05, 2.0822e-05],
         ...,
         [9.9468e-01, 1.5201e-03, 1.3626e-03,  ..., 7.3196e-04,
          4.048

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 1],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9550e-01, 5.4803e-04, 4.8116e-04,  ..., 1.3896e-04,
          7.0311e-05, 1.0136e-04],
         [9.7647e-01, 2.9980e-03, 2.6178e-03,  ..., 7.9098e-04,
          1.0101e-03, 3.5858e-04],
         [9.4048e-01, 5.3217e-03, 4.0747e-03,  ..., 1.8144e-03,
          4.8322e-04, 1.2965e-03],
         ...,
         [9.9392e-01, 1.0009e-03, 8.0245e-04,  ..., 3.0359e-04,
          1.6422e-04, 9.4687e-05],
         [9.9479e-01, 1.0893e-03, 7.4470e-04,  ..., 2.1779e-04,
          1.8852e-04, 8.8019e-05],
         [9.8110e-01, 3.6314e-03, 3.1835e-03,  ..., 8.9278e-04,
          5.0129e-04, 3.6798e-04]],

        [[9.9726e-01, 5.2830e-04, 4.4197e-04,  ..., 2.0966e-04,
          1.2410e-04, 3.2306e-0


batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 2, 2,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 1],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9659e-01, 8.9953e-04, 3.1014e-04,  ..., 3.7280e-04,
          3.3501e-04, 1.5608e-05],
         [9.8188e-01, 5.1752e-04, 2.8056e-04,  ..., 3.3185e-03,
          1.0941e-03, 1.4562e-05],
         [9.8904e-01, 2.1872e-04, 1.6941e-04,  ..., 2.6877e-05,
          3.4445e-04, 6.1080e-06],
         ...,
         [9.9380e-01, 2.1841e-03, 8.1482e-04,  ..., 9.1482e-04,
          3.1563e-04, 4.3107e-05],
         [9.9501e-01, 1.6009e-03, 6.7146e-04,  ..., 8.0084e-04,
          3.3110e-04, 3.9345e-05],
         [9.8170e-01, 5.5513e-03, 2.6064e-03,  ..., 3.4743e-03,
          1.1088e-03, 1.0253e-04]],

        [[9.9708e-01, 6.0622e-04, 2.7916e-04,  ..., 3.8372e-04,
          1.1783e-04, 8.6854e-

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 4,  ..., 0, 0, 0],
        [0, 0, 9,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 1],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.8751e-01, 5.6595e-03, 1.3506e-03,  ..., 3.8842e-04,
          2.8556e-05, 9.7057e-05],
         [9.8603e-01, 2.7682e-03, 8.9133e-04,  ..., 2.3332e-04,
          9.2509e-05, 2.0293e-04],
         [9.8671e-01, 1.0652e-03, 3.7881e-04,  ..., 3.0234e-04,
          1.1051e-04, 5.8562e-05],
         ...,
         [3.2715e-02, 8.5354e-01, 8.0020e-02,  ..., 3.3823e-03,
          2.5345e-05, 1.3393e-03],
         [1.1740e-01, 7.6421e-01, 6.0094e-02,  ..., 2.4708e-03,
          2.7630e-05, 1.1214e-03],
         [1.4730e-01, 7.2351e-01, 5.0722e-02,  ..., 4.8220e-03,
          2.3353e-04, 1.9392e-03]],

        [[9.9821e-01, 6.8140e-04, 8.1383e-05,  ..., 7.5243e-05,
          5.9759e-05, 2.0977e-0

batch_preds torch.Size([32, 128]) tensor([[ 0,  0,  0,  ...,  1,  1,  1],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  9,  9,  ...,  0,  0,  0],
        ...,
        [ 0,  0,  0,  ...,  0,  0,  1],
        [ 0,  0, 14,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0]], device='cuda:0')
torch.Size([32, 128, 16])


tensor([[[9.9590e-01, 8.0424e-04, 2.6779e-04,  ..., 4.7329e-04,
          1.9142e-04, 4.5758e-05],
         [9.8706e-01, 4.7262e-04, 2.0264e-04,  ..., 2.5956e-05,
          1.9427e-05, 6.0955e-05],
         [1.7768e-03, 1.0069e-05, 2.4575e-05,  ..., 1.7435e-03,
          9.8101e-06, 5.7656e-06],
         ...,
         [9.8066e-01, 4.3213e-03, 2.8304e-03,  ..., 2.1961e-03,
          3.4633e-04, 2.5955e-04],
         [9.7598e-01, 5.8889e-03, 3.0538e-03,  ..., 1.7609e-03,
          3.8602e-04, 3.5285e-04],
         [9.1197e-01, 2.1489e-02, 9.7462e-03,  ..., 2.4969e-03,
          9.4084e-04, 2.2651e-03]],

        [[9.9811e-01, 4.4235e-04, 2.2523e-04,  ..., 2.0244e-04,
          3.6424e-05, 2.3122e-05],
         [9.9929e-01, 1.0396e-04, 8.5612e-05,  ..., 1.0622e-04,
          4.1687e-05, 6.5939e-06],
         [9.9510e-01, 6.4279e-04, 1.4874e-04,  ..., 4.0901e-04,
          6.0172e-04, 7.6338e-05],
         ...,
         [9.9346e-01, 1.4967e-03, 1.2732e-03,  ..., 8.1530e-04,
          6.752

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 2, 2,  ..., 0, 0, 0],
        [0, 1, 5,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.7211e-01, 1.9520e-02, 2.7034e-03,  ..., 3.2153e-04,
          3.0049e-04, 6.7094e-05],
         [5.4657e-01, 2.1897e-01, 1.7383e-01,  ..., 2.1734e-03,
          1.1881e-03, 5.1563e-04],
         [9.9050e-01, 2.9762e-03, 3.4531e-03,  ..., 1.1922e-04,
          1.0152e-03, 3.1796e-05],
         ...,
         [9.8522e-01, 9.0855e-03, 3.0705e-03,  ..., 2.1175e-04,
          1.7338e-04, 4.8022e-05],
         [9.5740e-01, 2.4010e-02, 1.1750e-02,  ..., 5.7408e-04,
          2.3910e-04, 1.5589e-04],
         [7.8597e-01, 1.4114e-01, 4.4784e-02,  ..., 1.3607e-03,
          4.6947e-04, 6.5082e-04]],

        [[9.9565e-01, 1.3866e-03, 6.6361e-04,  ..., 9.7711e-04,
          7.4700e-05, 1.7200e-0

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 3, 3, 3],
        ...,
        [0, 1, 0,  ..., 0, 0, 1],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9598e-01, 1.2254e-03, 6.5692e-05,  ..., 3.8945e-04,
          1.0048e-04, 2.9627e-05],
         [9.7709e-01, 3.6155e-04, 6.2325e-05,  ..., 5.4923e-05,
          2.2806e-04, 1.5445e-05],
         [9.7407e-01, 2.9800e-04, 6.0278e-05,  ..., 4.7682e-05,
          1.2488e-04, 9.6460e-06],
         ...,
         [2.9183e-01, 6.5425e-01, 7.3462e-03,  ..., 1.0196e-03,
          2.3204e-04, 9.4742e-04],
         [9.9615e-02, 8.5271e-01, 8.6439e-03,  ..., 3.1647e-04,
          9.2897e-05, 9.2637e-04],
         [1.1633e-01, 8.3395e-01, 1.1224e-02,  ..., 3.0913e-04,
          1.0253e-04, 1.2073e-03]],

        [[9.8764e-01, 6.6653e-03, 4.0946e-04,  ..., 1.8101e-04,
          1.1257e-04, 8.6490e-0

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 1, 1, 1],
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 1, 2,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.8724e-01, 7.4520e-03, 8.8534e-04,  ..., 4.3295e-04,
          1.0651e-04, 6.2686e-05],
         [4.1532e-01, 5.1478e-01, 2.7647e-02,  ..., 1.8527e-03,
          3.9651e-04, 7.0452e-04],
         [9.8871e-01, 7.1378e-03, 6.7678e-04,  ..., 7.9911e-05,
          7.0878e-05, 6.2427e-05],
         ...,
         [9.4891e-01, 2.8924e-02, 6.2112e-03,  ..., 1.4692e-03,
          2.0221e-04, 3.5233e-04],
         [8.9659e-01, 9.1080e-02, 3.8777e-03,  ..., 1.3123e-03,
          1.8292e-05, 2.4993e-04],
         [9.7247e-01, 2.1659e-02, 7.9241e-04,  ..., 4.9422e-04,
          3.5873e-06, 5.1708e-05]],

        [[9.9414e-01, 1.3289e-03, 2.1338e-04,  ..., 8.6799e-04,
          2.9093e-04, 4.0211e-0

batch_preds torch.Size([32, 128]) tensor([[0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 1, 0, 1],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9034e-01, 6.3775e-03, 7.6893e-04,  ..., 4.4419e-04,
          7.2688e-05, 2.6830e-05],
         [1.7588e-01, 6.9716e-01, 1.0142e-01,  ..., 2.3101e-04,
          5.4759e-04, 1.1346e-03],
         [7.0012e-02, 6.5524e-01, 2.3196e-01,  ..., 7.0349e-04,
          9.5662e-04, 2.9548e-03],
         ...,
         [9.7257e-01, 1.9191e-02, 3.0907e-03,  ..., 8.7908e-04,
          1.5571e-04, 7.7022e-05],
         [9.5299e-01, 3.1910e-02, 4.9206e-03,  ..., 1.8722e-03,
          3.1117e-04, 1.4138e-04],
         [8.6705e-01, 8.4868e-02, 1.3024e-02,  ..., 5.8430e-03,
          9.5669e-04, 3.3224e-04]],

        [[9.9745e-01, 8.9201e-04, 2.1516e-04,  ..., 2.7984e-04,
          7.4019e-05, 1.1720e-0

batch_preds torch.Size([32, 128]) tensor([[0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 1, 1, 1],
        ...,
        [0, 0, 1,  ..., 4, 4, 4],
        [0, 1, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 2, 2, 6]], device='cuda:0')
torch.Size([32, 128, 16])


tensor([[[9.9724e-01, 9.7038e-04, 3.1590e-04,  ..., 2.6279e-04,
          1.4568e-04, 1.5470e-05],
         [4.1341e-01, 4.7030e-01, 8.4245e-02,  ..., 1.1863e-03,
          1.7398e-03, 8.3948e-04],
         [1.5415e-01, 6.3890e-01, 1.3809e-01,  ..., 1.5859e-03,
          9.2888e-04, 1.9973e-03],
         ...,
         [9.9301e-01, 2.3763e-03, 1.4845e-03,  ..., 8.8643e-04,
          1.7292e-04, 4.0899e-05],
         [9.8142e-01, 5.8266e-03, 4.3659e-03,  ..., 2.3146e-03,
          3.2738e-04, 1.0910e-04],
         [9.5338e-01, 1.6300e-02, 7.7547e-03,  ..., 6.5621e-03,
          9.7983e-04, 1.9193e-04]],

        [[9.9085e-01, 4.4000e-03, 7.8007e-04,  ..., 1.4659e-04,
          1.3877e-04, 7.6983e-05],
         [9.8784e-01, 4.0999e-03, 3.4334e-03,  ..., 8.6004e-05,
          1.2157e-04, 5.4221e-05],
         [9.8524e-01, 9.3601e-03, 2.0450e-03,  ..., 2.0489e-04,
          1.8615e-04, 4.3722e-05],
         ...,
         [9.7142e-01, 1.3765e-02, 3.7430e-03,  ..., 4.5367e-04,
          1.810

torch.Size([32, 128, 16])
tensor([[[9.9877e-01, 6.6673e-04, 6.2319e-05,  ..., 1.2713e-04,
          1.0115e-05, 2.4330e-06],
         [2.2814e-01, 7.5586e-01, 2.2891e-03,  ..., 1.3244e-03,
          7.1378e-04, 8.9224e-05],
         [9.0484e-01, 7.9680e-02, 4.2523e-03,  ..., 9.7868e-04,
          1.3493e-03, 3.0933e-04],
         ...,
         [9.8485e-01, 1.0964e-02, 7.0401e-04,  ..., 1.3037e-03,
          2.9507e-05, 1.6544e-05],
         [9.8798e-01, 8.6173e-03, 5.9285e-04,  ..., 9.8118e-04,
          2.7228e-05, 1.3492e-05],
         [5.9977e-01, 3.6170e-01, 7.2170e-03,  ..., 2.3006e-03,
          5.2497e-05, 9.0186e-05]],

        [[9.9722e-01, 9.7817e-04, 1.5726e-04,  ..., 1.2284e-04,
          5.9780e-05, 1.8566e-04],
         [9.9861e-01, 2.5861e-04, 6.2156e-05,  ..., 8.3572e-06,
          1.0713e-05, 2.6056e-04],
         [9.7272e-01, 5.0727e-03, 6.2156e-04,  ..., 3.1108e-05,
          2.5572e-04, 2.8961e-03],
         ...,
         [9.9015e-01, 4.5814e-03, 6.6033e-04,  ..., 3

tensor([[[9.9800e-01, 5.0947e-04, 2.8406e-04,  ..., 1.2677e-04,
          6.5189e-05, 2.1512e-05],
         [9.9596e-01, 3.0692e-04, 4.5926e-04,  ..., 1.6233e-04,
          8.9870e-04, 1.7619e-05],
         [1.7298e-02, 9.0259e-05, 1.0789e-04,  ..., 9.6663e-01,
          2.3132e-03, 4.5207e-06],
         ...,
         [9.8582e-01, 4.5182e-03, 3.3091e-03,  ..., 8.3265e-04,
          1.2686e-04, 1.5097e-04],
         [9.8810e-01, 3.8545e-03, 2.6745e-03,  ..., 5.0804e-04,
          1.0608e-04, 1.3086e-04],
         [5.5695e-01, 3.0175e-02, 2.4780e-01,  ..., 1.1485e-03,
          8.0001e-04, 9.5804e-03]],

        [[9.9823e-01, 3.4623e-04, 9.4199e-05,  ..., 1.0871e-04,
          1.0110e-04, 2.7719e-05],
         [9.2790e-01, 1.5901e-03, 3.8074e-03,  ..., 2.2572e-03,
          3.3919e-02, 1.0884e-02],
         [8.8991e-01, 8.1379e-03, 3.5026e-03,  ..., 8.4501e-04,
          5.4213e-04, 3.0158e-02],
         ...,
         [9.9063e-01, 1.7800e-03, 6.7885e-04,  ..., 6.0408e-04,
          2.140

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 6, 0, 6],
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 3, 0,  ..., 3, 0, 3],
        [0, 0, 0,  ..., 1, 0, 1],
        [0, 1, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9192e-01, 3.7476e-03, 4.1211e-04,  ..., 6.9912e-04,
          7.4091e-05, 5.8623e-05],
         [5.6436e-01, 3.4599e-01, 8.5702e-03,  ..., 6.3523e-03,
          4.6283e-04, 7.0146e-04],
         [9.9544e-01, 1.4412e-03, 4.8112e-04,  ..., 1.0823e-03,
          3.6673e-05, 3.1512e-05],
         ...,
         [9.7732e-01, 1.0077e-02, 2.2801e-03,  ..., 3.6688e-03,
          2.0775e-04, 1.7557e-04],
         [9.6776e-01, 1.2162e-02, 3.5952e-03,  ..., 5.7752e-03,
          2.3301e-04, 2.6566e-04],
         [8.9525e-01, 5.3590e-02, 6.9096e-03,  ..., 1.5273e-02,
          5.1434e-04, 6.4591e-04]],

        [[9.8947e-01, 1.5570e-03, 2.7578e-03,  ..., 5.2222e-04,
          3.0666e-04, 7.7047e-0


batch_preds torch.Size([32, 128]) tensor([[ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ..., 12, 12, 12],
        [ 0,  0,  6,  ...,  0,  0,  0],
        ...,
        [ 0,  0,  1,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9878e-01, 2.4126e-04, 1.1306e-04,  ..., 2.3484e-04,
          6.1674e-05, 1.5767e-05],
         [9.9750e-01, 1.2742e-04, 7.8625e-05,  ..., 2.7659e-05,
          1.2743e-04, 1.1378e-05],
         [9.9523e-01, 9.8282e-05, 4.6634e-05,  ..., 2.1233e-05,
          1.2470e-05, 5.9299e-06],
         ...,
         [5.4508e-02, 2.1514e-03, 1.1498e-02,  ..., 1.2723e-03,
          2.4124e-05, 4.9151e-03],
         [4.5664e-02, 1.7645e-03, 8.9669e-03,  ..., 7.4020e-04,
          1.2641e-05, 4.0646e-03],
         [5.8435e-02, 2.3175e-03, 1.0711e-02,  ..., 7.6274e-04,
          1.2838e-05, 4.3401e-03]],

        [[9.8505e-01, 7.8899e-03, 5.7376e-04,  ..., 2.6094

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 3, 3, 3],
        [0, 0, 0,  ..., 3, 0, 3],
        [0, 0, 0,  ..., 0, 0, 2],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 1, 0, 1],
        [0, 0, 2,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9734e-01, 6.0952e-04, 4.2809e-04,  ..., 2.6629e-04,
          7.0067e-05, 1.4031e-05],
         [9.7346e-01, 8.8014e-03, 1.5446e-03,  ..., 1.9851e-03,
          7.5991e-04, 1.0540e-04],
         [9.9884e-01, 2.3722e-04, 8.4112e-05,  ..., 1.1531e-04,
          5.0029e-05, 6.4030e-06],
         ...,
         [9.9378e-01, 5.7794e-04, 1.7154e-03,  ..., 1.1038e-03,
          1.6902e-04, 2.6696e-05],
         [9.9251e-01, 7.2890e-04, 1.9891e-03,  ..., 1.3983e-03,
          1.7040e-04, 3.3010e-05],
         [9.9504e-01, 7.2770e-04, 1.2648e-03,  ..., 8.4279e-04,
          1.8444e-04, 2.4331e-05]],

        [[9.9215e-01, 3.0293e-03, 9.9871e-04,  ..., 8.3128e-04,
          7.9333e-05, 3.5747e-0

batch_preds torch.Size([32, 128]) tensor([[ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  1,  0,  ...,  0,  0,  0],
        ...,
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0, 14,  ...,  3,  3,  3],
        [ 0,  0,  0,  ...,  0,  0,  0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9134e-01, 3.8160e-03, 4.8817e-04,  ..., 1.5897e-04,
          1.3442e-04, 7.9844e-05],
         [9.7963e-01, 1.5833e-02, 4.7802e-04,  ..., 8.9860e-05,
          1.2631e-03, 5.2179e-05],
         [9.8861e-01, 5.2434e-03, 3.8808e-04,  ..., 2.9374e-05,
          4.6321e-03, 2.9588e-05],
         ...,
         [9.9418e-01, 2.9235e-03, 3.5025e-04,  ..., 7.2188e-05,
          7.2189e-05, 7.3837e-05],
         [9.9060e-01, 4.1982e-03, 5.9803e-04,  ..., 1.4546e-04,
          1.8594e-04, 1.6584e-04],
         [7.6211e-01, 9.1120e-02, 1.9946e-02,  ..., 4.8507e-04,
          8.2181e-04, 4.1622e-03]],

        [[9.9054e-01, 3.2605e-03, 4.1031e-04,  ..., 1.3831e

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.7512e-01, 1.6201e-02, 2.5908e-03,  ..., 1.8581e-03,
          1.9430e-04, 8.8002e-05],
         [4.3336e-01, 4.8885e-01, 2.6522e-02,  ..., 1.5129e-02,
          4.0307e-03, 3.2637e-04],
         [9.7937e-01, 1.7768e-02, 7.2168e-04,  ..., 5.6150e-04,
          1.8620e-04, 2.3595e-05],
         ...,
         [9.8904e-01, 5.2319e-03, 4.1063e-03,  ..., 3.1039e-05,
          3.1237e-06, 3.1656e-05],
         [9.5516e-01, 2.4444e-02, 1.4490e-02,  ..., 1.2893e-04,
          9.3072e-06, 7.8171e-05],
         [8.6478e-01, 1.0902e-02, 9.0362e-02,  ..., 1.6560e-03,
          3.6734e-05, 1.1468e-04]],

        [[9.9692e-01, 1.4526e-03, 2.1627e-04,  ..., 9.0532e-05,
          7.8681e-05, 7.5072e-0

batch_preds torch.Size([32, 128]) tensor([[0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 1, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.6832e-01, 4.4396e-03, 5.2439e-03,  ..., 1.1537e-03,
          3.7021e-04, 5.2595e-04],
         [9.3213e-01, 4.2666e-03, 4.1345e-03,  ..., 2.2056e-03,
          7.5057e-04, 5.9133e-04],
         [6.9409e-01, 3.9527e-03, 6.7977e-03,  ..., 6.2583e-03,
          1.9241e-03, 1.4353e-03],
         ...,
         [3.4338e-01, 4.5197e-02, 1.5048e-01,  ..., 4.9786e-02,
          5.5514e-04, 2.6351e-02],
         [8.1412e-01, 6.5904e-03, 4.5745e-02,  ..., 1.0433e-02,
          1.3392e-03, 4.8742e-03],
         [6.1527e-01, 2.0669e-02, 9.1595e-02,  ..., 1.2157e-02,
          1.8087e-03, 8.3879e-03]],

        [[9.9726e-01, 4.4655e-04, 3.2274e-04,  ..., 1.9724e-04,
          1.1850e-04, 1.2834e-0

batch_preds torch.Size([32, 128]) tensor([[ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  4],
        [ 0,  0,  8,  ...,  0,  0,  0],
        ...,
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0, 13,  1,  ...,  0,  0,  0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9314e-01, 1.4061e-03, 3.1526e-03,  ..., 2.3798e-04,
          3.3966e-05, 2.7676e-04],
         [4.3183e-01, 5.2837e-02, 1.3494e-01,  ..., 2.5723e-03,
          3.3593e-04, 8.2657e-03],
         [9.4242e-01, 1.1700e-03, 3.1994e-02,  ..., 6.4532e-04,
          7.7700e-05, 2.2726e-03],
         ...,
         [9.7349e-01, 5.8808e-03, 1.1878e-02,  ..., 1.3881e-03,
          1.0542e-04, 7.1556e-04],
         [9.6076e-01, 9.6402e-03, 1.7210e-02,  ..., 1.5897e-03,
          1.0610e-04, 1.1147e-03],
         [4.1530e-02, 3.4094e-03, 1.6593e-02,  ..., 7.7424e-04,
          6.0661e-05, 1.1435e-03]],

        [[9.9871e-01, 4.2186e-04, 1.2019e-04,  ..., 1.9196e


batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 3],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 5,  ..., 0, 0, 0],
        ...,
        [0, 0, 9,  ..., 0, 0, 1],
        [0, 0, 9,  ..., 1, 0, 1],
        [0, 0, 9,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.8587e-01, 8.7583e-03, 8.9891e-04,  ..., 5.8336e-04,
          1.3729e-04, 5.6200e-05],
         [9.6357e-01, 2.3047e-02, 2.4587e-03,  ..., 7.3277e-04,
          6.7535e-05, 7.2278e-05],
         [9.0841e-01, 5.5310e-02, 7.6206e-03,  ..., 3.2956e-03,
          7.0978e-05, 1.2221e-04],
         ...,
         [1.8188e-01, 4.9688e-01, 2.1820e-01,  ..., 2.3749e-03,
          2.6401e-04, 3.3071e-03],
         [1.4177e-01, 7.9992e-01, 3.3403e-02,  ..., 1.1630e-03,
          5.5755e-04, 7.8862e-04],
         [8.1081e-01, 1.5952e-01, 8.5533e-03,  ..., 2.3173e-03,
          8.3078e-04, 4.0728e-04]],

        [[9.9583e-01, 1.4573e-03, 5.7125e-04,  ..., 1.9223e-04,
          8.6078e-05, 2.4444e-

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 1, 1, 0],
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 8, 8, 8],
        ...,
        [0, 0, 2,  ..., 0, 0, 0],
        [0, 0, 8,  ..., 0, 0, 0],
        [0, 1, 2,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.0351e-01, 2.5774e-03, 7.3628e-04,  ..., 4.6086e-04,
          2.4403e-04, 2.0751e-04],
         [6.2810e-01, 4.5509e-02, 8.6669e-03,  ..., 2.2860e-03,
          8.5858e-04, 1.5320e-03],
         [9.9687e-01, 2.5441e-04, 1.3185e-04,  ..., 4.4241e-05,
          3.0599e-04, 2.5470e-05],
         ...,
         [8.7575e-01, 9.2529e-03, 3.6739e-03,  ..., 1.7126e-03,
          8.2431e-04, 6.1905e-04],
         [8.8604e-01, 7.9737e-03, 3.2136e-03,  ..., 1.3440e-03,
          8.6645e-04, 5.5864e-04],
         [5.7670e-01, 2.2103e-02, 8.0057e-03,  ..., 3.6650e-03,
          7.3514e-04, 1.5733e-03]],

        [[9.9945e-01, 2.2150e-04, 3.2171e-05,  ..., 6.3927e-05,
          2.7398e-05, 3.0067e-0


batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 2, 2, 2],
        [0, 0, 9,  ..., 0, 0, 0],
        ...,
        [0, 1, 2,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 2, 2,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9438e-01, 1.3803e-03, 7.1326e-04,  ..., 4.7230e-04,
          9.7527e-05, 3.1508e-05],
         [9.9160e-01, 3.7640e-03, 3.2733e-04,  ..., 1.0124e-03,
          7.2062e-05, 2.1448e-05],
         [9.9750e-01, 4.6115e-04, 1.7014e-04,  ..., 4.7746e-04,
          7.8724e-06, 1.1931e-05],
         ...,
         [7.6880e-01, 7.7061e-02, 4.8640e-02,  ..., 2.6915e-03,
          7.2696e-04, 8.4247e-04],
         [9.5208e-01, 1.6843e-02, 9.7027e-03,  ..., 2.3014e-03,
          3.6337e-04, 3.3284e-04],
         [5.2050e-01, 1.4144e-01, 1.1007e-01,  ..., 3.4580e-03,
          8.6072e-04, 1.4919e-03]],

        [[9.8444e-01, 1.3273e-03, 5.0815e-04,  ..., 8.7460e-04,
          7.3611e-04, 6.4715e-

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 2,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])


tensor([[[9.9538e-01, 1.5100e-03, 6.0316e-04,  ..., 6.3507e-04,
          1.4908e-04, 1.4069e-05],
         [5.1392e-01, 4.2132e-01, 2.2014e-02,  ..., 1.7167e-02,
          2.2447e-03, 2.1867e-04],
         [8.1810e-01, 1.2961e-01, 9.5150e-03,  ..., 2.0915e-03,
          6.0510e-04, 1.6613e-04],
         ...,
         [9.8999e-01, 2.8747e-03, 2.5523e-03,  ..., 1.4522e-03,
          2.8572e-04, 3.7986e-05],
         [9.9122e-01, 2.4716e-03, 2.2789e-03,  ..., 1.1868e-03,
          2.7550e-04, 3.4788e-05],
         [1.7040e-01, 1.7314e-03, 4.2545e-03,  ..., 6.4724e-01,
          1.4403e-01, 6.9641e-05]],

        [[9.9941e-01, 2.2224e-04, 3.8883e-05,  ..., 6.8751e-05,
          1.7782e-05, 3.9636e-06],
         [9.9829e-01, 1.5641e-04, 3.9519e-05,  ..., 1.3673e-05,
          2.2431e-05, 2.9895e-06],
         [9.8395e-01, 3.7927e-04, 2.1271e-04,  ..., 6.9557e-05,
          4.8301e-05, 1.4643e-05],
         ...,
         [9.9816e-01, 8.3133e-04, 2.0806e-04,  ..., 1.3147e-04,
          4.472

batch_preds torch.Size([32, 128]) tensor([[ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        ...,
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0, 14,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9811e-01, 5.9729e-04, 2.3687e-04,  ..., 1.3642e-04,
          2.7362e-05, 8.2655e-05],
         [9.9090e-01, 6.4295e-04, 5.2555e-05,  ..., 2.7780e-05,
          1.8991e-05, 2.1876e-05],
         [3.0928e-01, 5.9724e-04, 1.5266e-04,  ..., 5.9550e-05,
          8.6277e-05, 4.3354e-05],
         ...,
         [9.9765e-01, 7.9756e-04, 3.7027e-04,  ..., 2.9266e-04,
          4.7057e-05, 6.6919e-05],
         [9.9590e-01, 1.2502e-03, 7.4725e-04,  ..., 6.5256e-04,
          5.3344e-05, 1.1359e-04],
         [9.9440e-01, 1.3570e-03, 8.5947e-04,  ..., 8.7842e-04,
          8.7209e-05, 1.3303e-04]],

        [[9.9850e-01, 5.5429e-04, 1.5321e-04,  ..., 1.2957e

batch_preds torch.Size([32, 128]) tensor([[ 0,  0,  9,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0, 13],
        [ 0,  0,  0,  ...,  0,  0,  1],
        ...,
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  1,  1,  0],
        [ 0,  0,  0,  ...,  0,  0,  0]], device='cuda:0')
torch.Size([32, 128, 16])


tensor([[[9.9418e-01, 2.7137e-03, 2.5683e-04,  ..., 2.2465e-04,
          6.3324e-05, 7.0795e-05],
         [9.9081e-01, 3.0137e-03, 6.4133e-04,  ..., 6.6509e-04,
          2.1960e-04, 1.0237e-04],
         [9.8541e-01, 4.1324e-03, 4.9604e-04,  ..., 9.5950e-04,
          5.0677e-04, 1.4071e-04],
         ...,
         [9.9335e-01, 2.7920e-03, 4.6425e-04,  ..., 2.4735e-04,
          9.2004e-05, 8.9607e-05],
         [9.9089e-01, 4.1057e-03, 6.0717e-04,  ..., 2.9767e-04,
          7.3286e-05, 1.2434e-04],
         [9.9427e-01, 2.6068e-03, 3.6299e-04,  ..., 2.0931e-04,
          8.7144e-05, 7.7094e-05]],

        [[9.9359e-01, 2.1762e-03, 6.1740e-04,  ..., 3.9344e-04,
          1.2404e-04, 6.1039e-05],
         [2.4389e-01, 5.8624e-01, 7.5421e-02,  ..., 1.3762e-03,
          1.0828e-03, 2.7839e-03],
         [1.0375e-01, 6.3230e-01, 1.0011e-01,  ..., 2.4938e-03,
          9.7316e-04, 3.0800e-03],
         ...,
         [9.9000e-01, 4.1289e-03, 9.3911e-04,  ..., 6.1525e-04,
          1.89

tensor([[[9.9468e-01, 6.5526e-04, 7.2201e-05,  ..., 1.3438e-04,
          2.9813e-05, 1.5142e-05],
         [8.0188e-01, 4.8610e-02, 4.3804e-03,  ..., 1.2193e-02,
          1.5637e-02, 4.7108e-04],
         [8.2839e-01, 4.6731e-02, 2.4370e-03,  ..., 2.8809e-02,
          1.1514e-03, 3.9910e-04],
         ...,
         [9.3712e-01, 1.6366e-02, 2.2527e-03,  ..., 4.9469e-03,
          5.2271e-04, 2.3770e-04],
         [9.4726e-01, 1.4150e-02, 1.3346e-03,  ..., 3.1515e-03,
          6.9111e-04, 1.4434e-04],
         [8.9714e-01, 2.3578e-02, 2.0148e-03,  ..., 4.7388e-03,
          7.9083e-04, 1.9184e-04]],

        [[9.9747e-01, 2.4554e-04, 3.4682e-04,  ..., 3.9285e-04,
          1.0516e-04, 1.2232e-05],
         [9.8223e-01, 2.2028e-03, 7.6405e-03,  ..., 5.7408e-04,
          2.3472e-04, 1.5060e-04],
         [8.6547e-01, 1.0094e-02, 8.6947e-02,  ..., 9.9732e-03,
          5.6234e-04, 8.2926e-04],
         ...,
         [9.2967e-01, 5.4876e-03, 3.7966e-02,  ..., 2.8780e-03,
          3.259

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 3],
        [0, 0, 0,  ..., 0, 0, 5],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])


tensor([[[9.8898e-01, 3.3959e-03, 2.3081e-03,  ..., 4.8417e-04,
          9.6304e-05, 2.1213e-04],
         [3.7593e-01, 2.0748e-01, 3.2743e-01,  ..., 1.3575e-03,
          1.0086e-03, 7.9392e-03],
         [2.0006e-01, 1.6134e-01, 4.6006e-01,  ..., 2.0097e-03,
          8.7813e-04, 1.2940e-02],
         ...,
         [9.8247e-01, 6.0135e-03, 4.5343e-03,  ..., 1.1191e-03,
          1.2415e-04, 3.4485e-04],
         [9.8019e-01, 6.6623e-03, 5.4040e-03,  ..., 1.2282e-03,
          1.3293e-04, 4.3054e-04],
         [8.0259e-01, 5.1103e-02, 7.8625e-02,  ..., 4.8215e-03,
          4.8750e-04, 5.7254e-03]],

        [[9.9694e-01, 1.5361e-03, 1.2248e-04,  ..., 4.9531e-05,
          8.6340e-05, 2.3772e-05],
         [8.8127e-01, 8.1698e-02, 5.5508e-03,  ..., 5.8444e-04,
          1.6678e-03, 4.7407e-04],
         [9.9865e-01, 5.1485e-04, 9.8212e-05,  ..., 1.2678e-05,
          1.5027e-04, 1.3490e-05],
         ...,
         [9.7360e-01, 1.5702e-02, 1.3839e-03,  ..., 3.2157e-04,
          3.850

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 2, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 4, 4, 4]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.9695e-01, 4.9601e-04, 5.1552e-05,  ..., 2.3759e-04,
          2.7751e-04, 1.5952e-05],
         [9.0841e-01, 7.0476e-04, 1.5631e-04,  ..., 2.1281e-03,
          8.2421e-02, 3.6961e-05],
         [8.5758e-01, 1.9279e-03, 1.3586e-04,  ..., 6.0902e-03,
          1.2065e-01, 8.6684e-05],
         ...,
         [9.8365e-01, 8.3441e-03, 8.7358e-04,  ..., 1.1962e-03,
          7.9014e-05, 2.1708e-04],
         [9.8342e-01, 1.0170e-02, 5.7056e-04,  ..., 8.2302e-04,
          1.3811e-04, 1.2115e-04],
         [3.5821e-01, 6.0983e-02, 1.1128e-01,  ..., 1.9219e-03,
          2.1082e-04, 3.3180e-01]],

        [[9.9279e-01, 3.6529e-03, 2.7871e-04,  ..., 2.5338e-04,
          2.9658e-04, 4.3721e-0

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([32, 128, 16])
tensor([[[9.6357e-01, 4.2597e-03, 9.3866e-04,  ..., 3.0103e-03,
          1.6618e-04, 1.4352e-04],
         [7.5458e-01, 7.1928e-02, 1.1734e-02,  ..., 3.1934e-03,
          1.3889e-03, 3.6656e-03],
         [4.5988e-01, 3.3778e-01, 2.7927e-02,  ..., 5.0878e-03,
          4.3704e-04, 1.1057e-02],
         ...,
         [8.9153e-01, 3.6694e-02, 8.0496e-03,  ..., 2.9409e-03,
          4.0573e-04, 9.4673e-04],
         [8.8738e-01, 3.9331e-02, 8.2197e-03,  ..., 2.6525e-03,
          3.9728e-04, 1.1292e-03],
         [9.0189e-01, 2.4985e-02, 9.0087e-03,  ..., 1.8327e-03,
          3.1113e-04, 2.0193e-03]],

        [[9.9091e-01, 4.6301e-03, 1.1763e-03,  ..., 2.9832e-04,
          1.5108e-04, 6.4070e-0

78it [00:14,  5.30it/s]
  0%|          | 0/20 [00:15<?, ?it/s]

batch_preds torch.Size([32, 128]) tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 1, 5,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0')
torch.Size([2, 128, 16])
tensor([[[9.9739e-01, 5.8433e-04, 6.3639e-04,  ..., 1.6886e-04,
          1.8740e-05, 1.2141e-04],
         [9.5951e-01, 3.8278e-03, 4.2610e-03,  ..., 1.4553e-04,
          6.9278e-05, 2.4018e-03],
         [9.1895e-01, 9.4173e-03, 8.2565e-03,  ..., 1.8268e-04,
          1.3885e-05, 7.6297e-03],
         ...,
         [9.8696e-01, 2.9545e-03, 2.8690e-03,  ..., 6.1867e-04,
          5.9037e-05, 4.4296e-04],
         [9.9158e-01, 2.0693e-03, 1.9895e-03,  ..., 3.1930e-04,
          5.6416e-05, 2.9754e-04],
         [9.9168e-01, 2.2763e-03, 1.7373e-03,  ..., 4.6320e-04,
          4.8136e-05, 3.7077e-04]],

        [[9.8950e-01, 5.3997e-03, 8.7781e-04,  ..., 4.8450e-04,
          1.9894e-04, 1.1653e-04

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
class TestDataset(Dataset):
    def __init__(self, X, tokenizer):
        self.tokenizer = tokenizer
        self.X = X
            
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        text = self.X[idx]
        
        # preprocess text
        # Remove cedilla diacritics as suggested in
        # https://huggingface.co/dumitrescustefan/bert-base-romanian-uncased-v1
        text = [
            word.replace("ţ", "ț").replace("ş", "ș").replace("Ţ", "Ț").replace("Ş", "Ș") 
            for word in text
        ]
        
        text = ['CLS'] + text + ['SEP']
        mask = [1] * len(text)
        
        padding_len = 128 - len(text)
        text += ['PAD'] * padding_len
        mask += [0] * padding_len
        
        text_tensor = torch.tensor(self.tokenizer.convert_tokens_to_ids(text))
        
        return text_tensor, torch.tensor(mask)

In [727]:
SEP_TOKEN = tokenizer.convert_tokens_to_ids('[SEP]')
SEP_TOKEN

3

In [731]:
def test(model, dataloader):    
    # Put the model in eval mode
    model.eval()
    preds = []
    
    with torch.no_grad():
        for idx, batch in tqdm(enumerate(dataloader)):            
            inputs, masks = batch
            # Move data to GPU
            inputs = inputs.to(device)
            # print(inputs.shape) # 32, 128
            masks = masks.to(device)
            # print(masks)            
            output, _ = model(ids=inputs, mask=masks, target_tag=None)
            
            probs = F.softmax(output, dim=-1) # TODO Incercat si cu dim=2
            batch_preds = torch.argmax(probs, dim=2)
            
            logits = batch_preds.detach().cpu().numpy()
            
            for i, input in enumerate(inputs):
                nr = 0
                for j, m in enumerate(input):
                    if j == 0:
                        # sar peste CLS
                        continue
                    # elif inputs[i][j] == SEP_TOKEN:
                    elif masks[i][j] == 0:
                        # print('BUNA')
                        preds = preds[:-1]
                        break
                    else:
                        nr += 1
                        preds.append(logits[i][j])
                # print(f'am dat append de {nr} ori')
            # preds.append(batch_preds.cpu().numpy())
    
    # preds = np.concatenate(preds)
    
    return preds

In [732]:
X_test = [data['tokens'] for data in test_data]
ds_test = TestDataset(X_test, tokenizer)

test_dataloader = DataLoader(
    ds_test, 
    sampler=SequentialSampler(ds_test), 
    batch_size=BATCH_SIZE,
    shuffle=False
)

best_model = TransformerModel().to(device)
best_model.load_state_dict(torch.load('./better_transformer_model.pt'))

preds = test(best_model, test_dataloader)

Some weights of the model checkpoint at dumitrescustefan/bert-base-romanian-uncased-v1 were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
76it [00:18,  4.13it/s]


In [733]:
len(preds)

73276

In [735]:
preds

[1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 11,
 11,
 11,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 9,
 9,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 

In [725]:
len(test_data)

2421

In [736]:
import csv

predictions_list = [[fst, snd] for fst, snd in preds]

out = csv.writer(open("predictii23-51.csv","w"), delimiter=',')
out.writerows(predictions_list)

TypeError: cannot unpack non-iterable numpy.int64 object

In [ ]:
f = open("results.csv", "w")
for i, pred in enumerate(preds):
    f.write(str(i) + ',' + str(pred) + '\n')